### ISSUE TITLE
Unable to connect to database: SequelizeConnectionError: role "postgres" does not exist

### ISSUE THREAD

**Issue by connor11528** [johnkariuki/bookmark#2]
I am running on Mac and tried to fire up this project. When I run the migration command I get an error that says I cannot connect to database. 

```
$ sequelize db:migrate 

Sequelize [Node: 6.0.0, CLI: 2.4.0, ORM: 3.24.1]

(node:62574) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Loaded configuration file "server/config/config.js".
Using environment "development".
Unable to connect to database: SequelizeConnectionError: role "postgres" does not exist
```

I think I need to create and setup the database. What are the steps I need to do this?

Based on the [SO post](http://stackoverflow.com/questions/21122598/postgres-user-does-not-exist)  I ran these commands:

```
$ psql -U postgres
psql: FATAL:  role "postgres" does not exist

$ psql
psql: FATAL:  database "connorleech" does not exist
```

How do I set up the postgres database and connect this app to it? Thank you

**Comment by johnkariuki** [comment]
If you take a look at `/server/config/config.js`, you will notice that the postgres connection Url is `postgres://postgres:password@localhost:5432/bookmark`.

This means that the Postgtress database `bookmark` connects through a user/role `postgres`. 
You can either.

Edit the url to match a user/role that exists in your psql setup.
`postgres://<custom_role>:password@localhost:5432/bookmark`

OR

Create the Postgres role using the psql command and assign the bookmark database to your new user;
- Login to the Postgres prompt interface:
  `psql`
- Create a new role
  `CREATE ROLE new_role;`
- Assign the new role to your database
  `GRANT ALL PRIVILEGES ON DATABASE bookmark to new_role`

I hope this helps @connor11528

**Comment by connor11528** [comment]
Okay cool! Thanks for the help setting up Postgres. This has been an issue with my getting started with SQL databases but now it's on. Thank you

**Comment by johnkariuki** [comment]
If you have any other issues just let me know and I will help you through it. @connor11528
